spring:
  application:
    name: lernix-server

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        jdbc:
          time_zone: Asia/Seoul

app:
  cdn:
    base-url: ${APP_CDN_BASE_URL}
file:
  storage:
    base-path: ${FILE_STORAGE_BASE_PATH}
    public-url-prefix: ${FILE_STORAGE_PUBLIC_URL_PREFIX}

minio:
  bucket: ${MINIO_BUCKET}
  endpoint: "http://${MINIO_HOST}:${MINIO_PORT}"
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  resource_expire_seconds: 120

cloud:
  aws:
    s3:
      bucket: ${CLOUD_S3_BUCKET}
      expire_seconds: ${CLOUD_S3_EXPIRE_SECONDS}
    stack.auto: false
    region.static: ${CLOUD_S3_REGION_STATIC}
    credentials:
      access-key: ${CLOUD_S3_ACCESS_KEY}
      secret-key: ${CLOUD_S3_SECRET_KEY}

storage:
  type: ${STORAGE_TYPE}