##########################################
### 결제 API (/api/payments)
##########################################

### 1. 결제 준비 (주문 항목 기반으로 주문 생성 및 결제 준비)
### 강좌 생성 API를 먼저 실행 후 응답으로 받은 courseId를 Request Body에 넣어주세요!
POST {{baseUrl}}/api/payments/prepare
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
  "items": [
    {
      "courseId": 101
    }
  ]
}

### 2. 결제 완료
POST {{baseUrl}}/api/payments/confirm
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{

}