INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (1, null, '드로잉', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (2, 1, '기초 드로잉', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (3, 1, '수채화', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (4, 1, '인물화', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (5, 1, '아이패드 드로잉', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (6, 1, '프로크리에이트', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (7, 1, '캐릭터 일러스트', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (8, null, '공예', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (9, 8, '도예', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (10, 8, '가죽공예', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (11, 8, '자수·뜨개', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (12, 8, '캔들·비누', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (13, null, '요리·음료', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (14, 13, '한식', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (15, 13, '베이킹', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (16, 13, '커피·디저트', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (17, 13, '음료·칵테일', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (18, null, '음악', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (19, 18, '보컬', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (20, 18, '기타', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (21, 18, '피아노', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (22, 18, '작곡·미디', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (23, null, '사진·영상', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (24, 23, '사진 촬영', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (25, 23, '영상 편집', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (26, 23, '유튜브 촬영·운영', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (27, null, '금융·재테크', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (28, 27, '주식·ETF', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (29, 27, '부동산', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (30, 27, '가계부·예산관리', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (31, 27, '세금·절세', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (32, null, '창업·부업', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (33, 32, '스마트스토어', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (34, 32, '쿠팡파트너스', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (35, 32, '브랜딩·SNS 마케팅', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (36, null, '성공 마인드', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (37, 36, '자기계발', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (38, 36, '시간관리', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (39, 36, '업무 효율화', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (40, null, 'AI 스킬업', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (41, 40, 'ChatGPT', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (42, 40, '생성형 AI', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (43, 40, 'AI 자동화', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (44, null, '프로그래밍', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (45, 44, '웹개발', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (46, 44, '프론트엔드', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (47, 44, '백엔드', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (48, 44, '모바일 앱', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (49, 44, '알고리즘·자료구조', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (50, null, '데이터사이언스', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (51, 50, '데이터 분석', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (52, 50, '파이썬 데이터', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (53, 50, '머신러닝', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (54, 50, '딥러닝', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (55, null, '기획', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (56, 55, 'UX 기획', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (57, 55, '서비스 기획', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (58, 55, '프로덕트 매니지먼트', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (59, null, '비즈니스', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (60, 59, '프로젝트 관리', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (61, 59, '스타트업 운영', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (62, 59, 'OKR·성과 관리', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (63, null, '생산성', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (64, 63, '노션·툴 활용', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (65, 63, '자동화·매크로', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (66, 63, '업무 효율화', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (67, null, '마케팅', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (68, 67, '디지털 마케팅', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (69, 67, '광고·퍼포먼스', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (70, 67, '콘텐츠 마케팅', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (71, 67, 'SNS 브랜딩', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (72, null, '디자인', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (73, 72, 'UX/UI 디자인', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (74, 72, '그래픽 디자인', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (75, 72, '피그마·포토샵', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (76, null, '영상/3D', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (77, 76, '프리미어 프로', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (78, 76, '애프터이펙트', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (79, 76, '3D 모델링·블렌더', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (80, null, '영어', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (81, 80, '회화', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (82, 80, '비즈니스 영어', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (83, 80, '발음·리스닝', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (84, 80, '문법·독해', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (85, null, '외국어 시험', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (86, 85, '토익', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (87, 85, '토플', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (88, 85, '오픽', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (89, 85, '아이엘츠', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (90, 85, 'JLPT', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (91, 85, 'HSK', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (92, 85, '기타 시험', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (93, null, '제2 외국어', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (94, 93, '일본어', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (95, 93, '중국어', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (96, 93, '스페인어', NOW(), NOW());
INSERT IGNORE INTO categories (id, parent_id, name, created_at, updated_at) VALUES (97, 93, '프랑스어', NOW(), NOW());